Chore: [AEA-0000] - devcontainer fail fast, posix equality, force docker gid (#2361)
## Summary

- Routine Change

### Details

- fail fast on RUN steps (use && instead of ;)
- posix-compliant equality (single = conditions)
- permit injection of docker group id if needed to resolve error on
starting the dev container:

```
Digital/eps-workflow-quality-checks/refs/tags/v4.0.4/dockerfiles/nhsd-git-secrets.dockerfile -t git-secrets . && poetry run pre-commit install --install-hooks -f
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
[9902 ms] postAttachCommand from devcontainer.json failed with exit code 1. Skipping any further user-provided commands.
```